name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  forge-tests:
    name: Forge Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: './test/js-scripts'
          cache: 'yarn'

      - run: yarn
        working-directory: ./test/js-scripts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8f1998e9878d786675189ef566a2e4bf24869773
        with:
          version: nightly

      - name: Build
        run: forge build
        env:
          FOUNDRY_PROFILE: ci

      - name: Run tests
        run: forge test -vvv
        env:
          FOUNDRY_PROFILE: ci
          
